package main

import (
	"go/ast"
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"strconv"
	"strings"
	"testing"
)

func parseFile(t *testing.T, src string) (*ast.File, *token.FileSet) {
	t.Helper()
	fset := token.NewFileSet()
	f, err := parser.ParseFile(fset, "model_x.go", src, parser.ParseComments)
	if err != nil {
		t.Fatalf("parse: %v", err)
	}
	return f, fset
}

func TestRelaxRequiredProperties(t *testing.T) {
	src := `// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package server

// UnmarshalJSON -
func (o *Widget) UnmarshalJSON(data []byte) (err error) {
	requiredProperties := []string{
		"Id",
		"Name",
		"Status",
	}
	_ = requiredProperties
	return nil
}
`
	f, fset := parseFile(t, src)

	changed := relaxRequiredProperties(f, "Id", "Name")
	if !changed {
		t.Fatal("expected relaxRequiredProperties to report a change")
	}

	var b strings.Builder
	if err := writeFile(&b, fset, f); err != nil {
		t.Fatalf("writeFile: %v", err)
	}
	got := b.String()

	if strings.Contains(got, `"Id"`) || strings.Contains(got, `"Name"`) {
		t.Errorf("Id/Name should have been removed:\n%s", got)
	}
	if !strings.Contains(got, `"Status"`) {
		t.Errorf("Status should have been left in place:\n%s", got)
	}
	if !strings.Contains(got, "Code generated by OpenAPI Generator") {
		t.Errorf("header comment was dropped:\n%s", got)
	}
	if !strings.Contains(got, "// UnmarshalJSON -") {
		t.Errorf("method doc comment was dropped:\n%s", got)
	}
}

func TestRelaxRequiredProperties_NoChangeNeeded(t *testing.T) {
	src := `package server

func (o *Widget) UnmarshalJSON(data []byte) (err error) {
	requiredProperties := []string{
		"Status",
	}
	_ = requiredProperties
	return nil
}
`
	f, _ := parseFile(t, src)
	if relaxRequiredProperties(f, "Id", "Name") {
		t.Error("expected no change when Id/Name aren't present")
	}
}

func TestRelaxRequiredProperties_IgnoresUnrelatedSlices(t *testing.T) {
	src := `package server

func f() {
	names := []string{"Id", "Name"}
	_ = names
}
`
	f, fset := parseFile(t, src)
	if relaxRequiredProperties(f, "Id", "Name") {
		t.Fatal("should not touch a slice that isn't named requiredProperties")
	}
	var b strings.Builder
	if err := writeFile(&b, fset, f); err != nil {
		t.Fatalf("writeFile: %v", err)
	}
	if !strings.Contains(b.String(), `"Id", "Name"`) {
		t.Errorf("unrelated slice was modified:\n%s", b.String())
	}
}

// TestRun_AgainstVendoredFiles guards the real, currently-generated
// models: every model whose UnmarshalJSON requires "Id" or "Name" (every
// type extending Redfish's Resource base) must have that requirement
// relaxed, since those fields are always server-assigned and no real
// Redfish client supplies them in a request body.
func TestRun_AgainstVendoredFiles(t *testing.T) {
	const dir = "../../../pkg/generated/redfish/server"
	entries, err := filepath.Glob(filepath.Join(dir, "model_*.go"))
	if err != nil || len(entries) == 0 {
		t.Skipf("vendored models not available: %v", err)
	}

	scratch := t.TempDir()
	for _, path := range entries {
		src, err := os.ReadFile(path)
		if err != nil {
			t.Fatalf("read %s: %v", path, err)
		}
		if err := os.WriteFile(filepath.Join(scratch, filepath.Base(path)), src, 0o644); err != nil {
			t.Fatalf("write scratch copy: %v", err)
		}
	}

	if _, err := run(scratch, "Id", "Name"); err != nil {
		t.Fatalf("run: %v", err)
	}

	// A repo where the fix is already committed sees this on every
	// subsequent `make generate-redfish-api`: running again against
	// already-relaxed output must be a no-op.
	if changed, err := run(scratch, "Id", "Name"); err != nil {
		t.Fatalf("second run: %v", err)
	} else if changed != 0 {
		t.Errorf("second run relaxed %d model(s), want 0 (not idempotent)", changed)
	}

	for _, path := range entries {
		out, err := os.ReadFile(filepath.Join(scratch, filepath.Base(path)))
		if err != nil {
			t.Fatalf("read scratch output: %v", err)
		}
		fset := token.NewFileSet()
		f, err := parser.ParseFile(fset, path, out, 0)
		if err != nil {
			t.Fatalf("parse scratch output for %s: %v", path, err)
		}
		ast.Inspect(f, func(n ast.Node) bool {
			assign, ok := n.(*ast.AssignStmt)
			if !ok || len(assign.Lhs) != 1 {
				return true
			}
			ident, ok := assign.Lhs[0].(*ast.Ident)
			if !ok || ident.Name != "requiredProperties" {
				return true
			}
			lit, ok := assign.Rhs[0].(*ast.CompositeLit)
			if !ok {
				return true
			}
			for _, elt := range lit.Elts {
				bl, ok := elt.(*ast.BasicLit)
				if !ok {
					continue
				}
				v, _ := strconv.Unquote(bl.Value)
				if v == "Id" || v == "Name" {
					t.Errorf("%s: requiredProperties still contains %q after relaxing", filepath.Base(path), v)
				}
			}
			return true
		})
	}
}
