#!/usr/bin/env sh
set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(cd "$SCRIPT_DIR/../../" && pwd)"
cd "$ROOT_DIR"

echo "Working directory: $(pwd)"

command -v openapi-generator || {
  echo "openapi-generator not found. Please install it first."
  exit 1
}

# goimports is used to post-process the generated code
command -v goimports || {
  echo "goimports not found. Please install it first."
  exit 1
}

if [ "$(uname)" = "Darwin" ]; then
    export JAVA_HOME=`/usr/libexec/java_home -v 1.11`
fi

# Trim the spec down to only the operations pkg/redfish actually implements,
# so openapi-generator doesn't generate stubs for the thousands it doesn't.
# See hack/redfish/spec/implemented-operations.yaml.
TRIMMED_SPEC="$(mktemp -t kubevirtbmc-redfish-openapi.XXXXXX).yaml"
trap 'rm -f "$TRIMMED_SPEC"' EXIT
go run ./hack/redfish/trim-redfish-spec \
    -input ./hack/redfish/spec/openapi.yaml \
    -allowlist ./hack/redfish/spec/implemented-operations.yaml \
    -output "$TRIMMED_SPEC"

# openapi-generator never deletes output from a previous run -- it only
# (re)writes whatever the current spec calls for. Without this, trimming the
# input spec would leave every model generated by a *previous*, less-trimmed
# run sitting untouched instead of actually shrinking pkg/generated/redfish.
rm -f ./pkg/generated/redfish/server/model_*.go

# Generate the models and server stubs from the trimmed OpenAPI spec
_JAVA_OPTIONS="-DmaxYamlCodePoints=99999999" GO_POST_PROCESS_FILE="goimports -w" openapi-generator generate \
    -i "$TRIMMED_SPEC" \
    -o ./pkg/generated/redfish/ \
    -g go-server \
    --package-name server \
    --enable-post-process-file \
    -p sourceFolder=server,onlyInterfaces=true,outputAsLibrary=true,enumClassPrefix=true

# openapi-generator's go-server template asserts every field an operation's
# schema marks "required" is present, which is wrong for PATCH: a PATCH body
# is a partial update by design. api_default.go now regenerates every run
# (it has to, so it can shrink along with the trimmed operation set), so this
# has to be reapplied every run too. See relax-patch-assertions for why.
go run ./hack/redfish/relax-patch-assertions \
    -file ./pkg/generated/redfish/server/api_default.go
goimports -w ./pkg/generated/redfish/server/api_default.go

# Every Redfish resource model requires "Id" and "Name" in its generated
# UnmarshalJSON, correct for a GET response but wrong for any request body a
# client sends: both fields are always server-assigned. Regenerates every
# run for the same reason as the assertion above. See
# relax-identity-required-fields for why.
go run ./hack/redfish/relax-identity-required-fields \
    -dir ./pkg/generated/redfish/server
goimports -w ./pkg/generated/redfish/server
